version: '3'

services:
  web:
    build:
      dockerfile: ./.docker/local/Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - '${PORT:-5000}:5000'
